import type { Channel } from '@/repository/channels'
import {
  LOGO_DARK_INK,
  LOGO_FULL_COLOUR,
  LOGO_NONE_BROADCAST,
  LOGO_NOT_YET_READ,
  LOGO_SOLID_BLOCK,
} from '@/repository/logos.fixtures'

export const CHANNEL_FIXTURES: Channel[] = [
  {
    id: '151-1511',
    no: '151',
    name: 'みなと総合1',
    kind: 'terrestrial',
    logo: LOGO_SOLID_BLOCK,
  },
  {
    id: '151-1521',
    no: '152',
    name: 'みなと総合2',
    kind: 'terrestrial',
    sub: true,
    whole: '151-1511',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '191-1911',
    no: '191',
    name: 'みなと教育1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '131-1311',
    no: '131',
    name: '中央テレビ1',
    kind: 'terrestrial',
    logo: LOGO_DARK_INK,
  },
  {
    id: '181-1811',
    no: '181',
    name: '第一テレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '171-1711',
    no: '171',
    name: '湾岸放送1',
    kind: 'terrestrial',
    logo: LOGO_NONE_BROADCAST,
  },
  {
    id: '161-1611',
    no: '161',
    name: '東都テレビ1',
    kind: 'terrestrial',
    logo: LOGO_FULL_COLOUR,
  },
  {
    id: '141-1411',
    no: '141',
    name: 'シティ MX1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
]

export const AERIAL_CHANNEL_FIXTURES: Channel[] = [
  ...CHANNEL_FIXTURES,
  {
    id: '31-311',
    no: '031',
    name: '内海テレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '31-321',
    no: '032',
    name: '内海テレビ2',
    kind: 'terrestrial',
    sub: true,
    whole: '31-311',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '41-411',
    no: '041',
    name: '房総テレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '51-511',
    no: '051',
    name: '武蔵テレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '61-611',
    no: '061',
    name: '甲斐テレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '71-711',
    no: '071',
    name: '上州テレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '81-811',
    no: '081',
    name: '相模テレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '91-911',
    no: '091',
    name: '常磐テレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '101-1011',
    no: '101',
    name: '北総放送1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '111-1111',
    no: '111',
    name: '西湘テレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '121-1211',
    no: '121',
    name: '多摩テレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '201-2011',
    no: '201',
    name: '港南放送1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '211-2111',
    no: '211',
    name: '江戸川テレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '221-2211',
    no: '221',
    name: '高原テレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '231-2311',
    no: '231',
    name: '潮騒放送1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '241-2411',
    no: '241',
    name: 'みどりテレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '251-2511',
    no: '251',
    name: '白樺テレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '261-2611',
    no: '261',
    name: '青葉テレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
  {
    id: '271-2711',
    no: '271',
    name: 'いずみテレビ1',
    kind: 'terrestrial',
    logo: LOGO_NOT_YET_READ,
  },
]
