import type { MigrationResult } from '@/repository/migration'

export const MIGRATION: MigrationResult = {
  run: {
    heading: '2026-08-10(日)03:12 の実行',
    kind: '本番',
    dryRuns: '下見 4 回 実施済み',
    startedAt: '2026-08-10 03:12:04',
    finishedAt: '03:18:46',
    duration: '所要 6 分 42 秒',
    source:
      '旧録画システムのデータベース(読み取り専用接続)/ 出力ディレクトリ /srv/legacy/recorded',
    dryRunNote:
      '本番。直前の下見は 2026-08-09 22:41 で、そのとき未分類は 0 件だった',
    output: '新しい出力ルート /srv/recordings',
  },
  populations: [
    {
      name: '録画',
      source: 'recorded',
      total: '53',
      unit: '本',
      taken: '51',
      notTaken: '2',
      unclassified: '0',
      link: { href: '/library', label: 'ライブラリで該当行を見る' },
    },
    {
      name: '録画ファイル',
      source: 'video_file + 出力ディレクトリ',
      total: '59',
      unit: '件',
      taken: '51',
      notTaken: '8',
      unclassified: '0',
      note: '移行元の行 53 + 孤児 6',
    },
    {
      name: 'ルール',
      source: 'rule',
      total: '17',
      unit: '件',
      taken: '16',
      notTaken: '1',
      unclassified: '0',
      link: {
        href: '/reservations/rules',
        label: 'ルール一覧で該当行を見る',
      },
    },
    {
      name: '予約',
      source: 'reserve',
      total: '14',
      unit: '件',
      taken: '0',
      notTaken: '14',
      unclassified: '0',
      note: '全件ルール由来。移行不要',
    },
    {
      name: 'チャンネル定義',
      source: 'channel',
      total: '39',
      unit: '件',
      taken: '35',
      notTaken: '4',
      unclassified: '0',
      note: '定義そのものは移行しない',
    },
  ],
  unclassified: '0',
  notTakenGroups: [
    {
      name: '実0バイト',
      count: '2',
      unit: '件',
      rows: [
        {
          id: 'nt-1',
          target: 'ETV 特集「記録する人々」',
          file: '2023-11-18_22-00-00.m2ts',
          population: '録画',
          fact: 'DB 上は 17,171,113,480 B。実ファイルは 0 B。手動録画',
        },
        {
          id: 'nt-2',
          target: '情熱の現場',
          file: '2024-02-04_23-00-00.m2ts',
          population: '録画',
          fact: 'DB 上は 5,208,028,640 B。実ファイルは 0 B。手動録画',
        },
      ],
    },
    {
      name: 'ファイル不在',
      count: '1',
      unit: '件',
      rows: [
        {
          id: 'nt-3',
          target: 'サムネイル',
          file: '4c1f9a2e.jpg',
          population: '録画ファイル',
          fact: '実ファイルが無い。本体の .m2ts は 2,877,458,022 B で正常に存在する。サムネイルは移行せず再生成するため、取り込みには影響しない',
        },
      ],
    },
    {
      name: '孤児',
      count: '6',
      unit: '件',
      rows: [
        {
          id: 'nt-4',
          file: '2026-05-03_23-00-00.m2ts.tmp',
          population: '録画ファイル',
          fact: '2,514,911,344 B。書きかけのまま残った一時ファイル',
        },
        {
          id: 'nt-5',
          file: '2026-06-17_01-30-00.m2ts.tmp',
          population: '録画ファイル',
          fact: '41,238,528 B。書きかけのまま残った一時ファイル',
        },
        {
          id: 'nt-6',
          file: '2026-02-11_19-00-00.m2ts',
          population: '録画ファイル',
          fact: '0 B。新しい出力ルートには現れない',
        },
        {
          id: 'nt-7',
          file: '2026-01-24_21-00-00.m2ts',
          population: '録画ファイル',
          fact: '727,013,296 B。中身はあるが、対応する行が存在しない',
        },
        {
          id: 'nt-8',
          file: 'bash.sh',
          population: '録画ファイル',
          fact: '539 B。録画ではない。出力ルートが誰でも書ける権限だったため混入した',
        },
        {
          id: 'nt-9',
          file: '9d3b7c15.jpg',
          population: '録画ファイル',
          fact: '82,314 B。対応する録画 ID が DB に存在しない',
        },
      ],
    },
    {
      name: '同定不能',
      count: '2',
      unit: '件',
      rows: [
        {
          id: 'nt-10',
          target: '「衛星の映画枠」ルール',
          file: 'rule id 12',
          population: 'ルール',
          fact: '参照しているチャンネルが再スキャン結果に無い。チャンネルが解決できないルールは作成せず、ここに報告する',
        },
        {
          id: 'nt-11',
          target: 'みなと教育2',
          file: 'channel id 27',
          population: 'チャンネル定義',
          fact: '再スキャン結果と名前対応が付かなかった。地上波の行には nid / sid が無いため、同定は原理的に不可能',
        },
      ],
    },
    {
      name: '型として表現不能',
      count: '3',
      unit: '件',
      rows: [
        {
          id: 'nt-12',
          target: '専用放送・ch161',
          file: 'channel id 40',
          population: 'チャンネル定義',
          fact: 'この種別は本システムの型に存在しない。破棄した定義として記録する',
        },
        {
          id: 'nt-13',
          target: '専用放送・ch171',
          file: 'channel id 41',
          population: 'チャンネル定義',
          fact: 'この種別は本システムの型に存在しない。破棄した定義として記録する',
        },
        {
          id: 'nt-14',
          target: '専用放送・ch181',
          file: 'channel id 42',
          population: 'チャンネル定義',
          fact: 'この種別は本システムの型に存在しない。破棄した定義として記録する',
        },
      ],
    },
    {
      name: '本システムに機能が無い',
      count: '0',
      unit: '件',
      rows: [],
      empty:
        '該当なし。この分類で落とした行はありません。項目単位で落とした avoidDuplicate は「やらなかったこと」に 1 行として記録しています',
    },
    {
      name: '対象外',
      count: '14',
      unit: '件',
      rows: [
        {
          id: 'nt-15',
          target: '深夜の商店街をあるく',
          file: '08/10(日)22:45 開始予定',
          population: '予約',
          fact: '全件ルール由来のため移行不要。ルールを有効化すると再び作られる',
          link: { href: '/reservations/rules', label: '由来のルールを見る' },
        },
        {
          id: 'nt-16',
          target: '世界の街かど',
          file: '08/11(月)19:30 開始予定',
          population: '予約',
          fact: '全件ルール由来のため移行不要。ルールを有効化すると再び作られる',
          link: { href: '/reservations/rules', label: '由来のルールを見る' },
        },
        {
          id: 'nt-17',
          target: 'コメット急行 #103',
          file: '08/11(月)23:00 開始予定',
          population: '予約',
          fact: '全件ルール由来のため移行不要。ルールを有効化すると再び作られる',
          link: { href: '/reservations/rules', label: '由来のルールを見る' },
        },
        {
          id: 'nt-18',
          target: 'クラシックの時間',
          file: '08/12(火)21:00 開始予定',
          population: '予約',
          fact: '全件ルール由来のため移行不要。ルールを有効化すると再び作られる',
          link: { href: '/reservations/rules', label: '由来のルールを見る' },
        },
        {
          id: 'nt-19',
          target: '手仕事の地図',
          file: '08/12(火)22:45 開始予定',
          population: '予約',
          fact: '全件ルール由来のため移行不要。ルールを有効化すると再び作られる',
          link: { href: '/reservations/rules', label: '由来のルールを見る' },
        },
        {
          id: 'nt-20',
          target: '週末キッチンの手帖',
          file: '08/13(水)20:00 開始予定',
          population: '予約',
          fact: '全件ルール由来のため移行不要。ルールを有効化すると再び作られる',
          link: { href: '/reservations/rules', label: '由来のルールを見る' },
        },
        {
          id: 'nt-21',
          target: '夜ふかしラジオ倶楽部',
          file: '08/14(木)22:45 開始予定',
          population: '予約',
          fact: '全件ルール由来のため移行不要。ルールを有効化すると再び作られる',
          link: { href: '/reservations/rules', label: '由来のルールを見る' },
        },
        {
          id: 'nt-22',
          target: 'となりの発明王',
          file: '08/14(木)19:30 開始予定',
          population: '予約',
          fact: '全件ルール由来のため移行不要。ルールを有効化すると再び作られる',
          link: { href: '/reservations/rules', label: '由来のルールを見る' },
        },
        {
          id: 'nt-23',
          target: '金曜シネマ「星の渡り鳥」',
          file: '08/15(金)21:00 開始予定',
          population: '予約',
          fact: '全件ルール由来のため移行不要。ルールを有効化すると再び作られる',
          link: { href: '/reservations/rules', label: '由来のルールを見る' },
        },
        {
          id: 'nt-24',
          target: '真夜中のトーク',
          file: '08/15(金)24:20 開始予定',
          population: '予約',
          fact: '全件ルール由来のため移行不要。ルールを有効化すると再び作られる',
          link: { href: '/reservations/rules', label: '由来のルールを見る' },
        },
        {
          id: 'nt-25',
          target: '世界の街かど',
          file: '08/16(土)19:30 開始予定',
          population: '予約',
          fact: '全件ルール由来のため移行不要。ルールを有効化すると再び作られる',
          link: { href: '/reservations/rules', label: '由来のルールを見る' },
        },
        {
          id: 'nt-26',
          target: '都市対抗クイズ選手権 準決勝',
          file: '08/16(土)12:30 開始予定',
          population: '予約',
          fact: '全件ルール由来のため移行不要。ルールを有効化すると再び作られる',
          link: { href: '/reservations/rules', label: '由来のルールを見る' },
        },
        {
          id: 'nt-27',
          target: 'ニュースの視点9',
          file: '08/17(日)21:00 開始予定',
          population: '予約',
          fact: '全件ルール由来のため移行不要。ルールを有効化すると再び作られる',
          link: { href: '/reservations/rules', label: '由来のルールを見る' },
        },
        {
          id: 'nt-28',
          target: '情熱の現場',
          file: '08/17(日)23:00 開始予定',
          population: '予約',
          fact: '全件ルール由来のため移行不要。ルールを有効化すると再び作られる',
          link: { href: '/reservations/rules', label: '由来のルールを見る' },
        },
      ],
    },
  ],
  omissions: [
    {
      id: 'om-1',
      tag: '対象外',
      title: '番組表',
      code: 'program',
      body: '移行対象外。7 日ぶんのローリング保持なので、新システムの EPG 再取得で復元します。[字] 置換の件も併せて下段に記録しています',
      count: '3,557',
      unit: '行',
    },
    {
      id: 'om-2',
      tag: '対象外',
      title: 'ルールの',
      code: 'avoidDuplicate',
      body: '本システムに存在しない項目です。現行で有効な行は 0 件ですが、対象外にしたことを記録に残さないと、後から機能欠落と区別できません',
      count: '17',
      unit: '件',
    },
    {
      id: 'om-3',
      tag: '対象が存在しない',
      title: '品質時系列',
      code: 'drop_log_file',
      body: '移行すべき品質時系列がそもそもありません。移行直後は録画 53 本すべてが「未計測」で並びます',
      count: '0',
      unit: '行',
    },
    {
      id: 'om-4',
      tag: '移行しない',
      title: '重複録画防止の履歴',
      code: 'recorded_history',
      body: '同じ番組を二度録らないための履歴です。移行しません',
      count: '230',
      unit: '行',
    },
    {
      id: 'om-5',
      tag: '移行しない',
      title: 'サムネイル',
      code: 'thumbnail',
      body: '移行せず、取り込みのあとに再生成します',
      count: '53',
      unit: '行',
    },
    {
      id: 'om-6',
      tag: '非可逆変化',
      title: '[字] 置換により原文復元不能',
      body: '移行元の番組名は [字] などの記号が置換された後の文字列で保存されており、原文を復元できません。移行後の番組名はこの置換済みの文字列のままです',
      count: '38',
      unit: '本',
    },
  ],
}
