import type { Program } from '@/repository/programs'

export const PROGRAM_FIXTURES: Program[] = [
  {
    id: 'p001',
    channelId: 'ch-151',
    title: 'みなと ニュース7',
    description: '列島の記録的暑さ 夜間も熱中症に警戒を',
    genre: 'news',
    genreLabel: 'ニュース/報道',
    startMin: 0,
    durationMin: 60,
    startLabel: '19:00',
    endLabel: '20:00',
  },
  {
    id: 'p002',
    channelId: 'ch-151',
    title: 'くらしの窓口',
    description: '夏の停電にそなえる',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
    startMin: 60,
    durationMin: 30,
    startLabel: '20:00',
    endLabel: '20:30',
  },
  {
    id: 'p003',
    channelId: 'ch-151',
    title: 'ヘッドラインニュース',
    genre: 'news',
    genreLabel: 'ニュース/報道',
    startMin: 90,
    durationMin: 30,
    startLabel: '20:30',
    endLabel: '21:00',
  },
  {
    id: 'p004',
    channelId: 'ch-151',
    title: 'ニュースの視点9',
    description: '電力需給対策のポイントを担当記者が解説',
    detail:
      '政府がまとめた電力需給対策のポイントを担当記者が詳しく解説。乱高下する為替が家計と中小企業に与える影響を取材。港町の美術館で始まった夜間開館の試みから、文化と観光の新しい関係を考える。',
    cast: ['司会 田無 千秋', '解説 秋川 みのり'],
    genre: 'news',
    genreLabel: 'ニュース/報道',
    startMin: 120,
    durationMin: 60,
    startLabel: '21:00',
    endLabel: '22:00',
    subtitled: true,
  },
  {
    id: 'p005',
    channelId: 'ch-151',
    title: '土曜ドラマ「灯台のある町」',
    description: '第5話 帰ってきた同級生',
    genre: 'drama',
    genreLabel: 'ドラマ',
    startMin: 180,
    durationMin: 90,
    startLabel: '22:00',
    endLabel: '23:30',
  },
  {
    id: 'p006',
    channelId: 'ch-151',
    title: '手仕事の地図',
    description: '町工場の職人たち',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    startMin: 270,
    durationMin: 60,
    startLabel: '23:30',
    endLabel: '00:30',
  },
  {
    id: 'p007',
    channelId: 'ch-151',
    title: '深夜のニュース',
    genre: 'news',
    genreLabel: 'ニュース/報道',
    startMin: 330,
    durationMin: 30,
    startLabel: '00:30',
    endLabel: '01:00',
  },
  {
    id: 'p008',
    channelId: 'ch-151',
    title: '真夜中の音楽室',
    description: '夏の弦楽四重奏',
    genre: 'music',
    genreLabel: '音楽',
    startMin: 360,
    durationMin: 120,
    startLabel: '01:00',
    endLabel: '03:00',
  },
  {
    id: 'p009',
    channelId: 'ch-152',
    title: '高校野球ダイジェスト',
    genre: 'sports',
    genreLabel: 'スポーツ',
    startMin: 0,
    durationMin: 120,
    startLabel: '19:00',
    endLabel: '21:00',
  },
  {
    id: 'p010',
    channelId: 'ch-152',
    title: 'データ気象台',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
    startMin: 120,
    durationMin: 120,
    startLabel: '21:00',
    endLabel: '23:00',
  },
  {
    id: 'p011',
    channelId: 'ch-152',
    title: '自然のしくみ 再放送',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    startMin: 240,
    durationMin: 240,
    startLabel: '23:00',
    endLabel: '03:00',
  },
  {
    id: 'p012',
    channelId: 'ch-191',
    title: 'はじめての天文学',
    description: '夏の大三角をさがす',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    startMin: 0,
    durationMin: 30,
    startLabel: '19:00',
    endLabel: '19:30',
  },
  {
    id: 'p013',
    channelId: 'ch-191',
    title: '手話ニュース',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
    startMin: 30,
    durationMin: 60,
    startLabel: '19:30',
    endLabel: '20:30',
  },
  {
    id: 'p014',
    channelId: 'ch-191',
    title: 'クラシックの時間',
    description: '夏の管弦楽',
    genre: 'music',
    genreLabel: '音楽',
    startMin: 90,
    durationMin: 90,
    startLabel: '20:30',
    endLabel: '22:00',
  },
  {
    id: 'p015',
    channelId: 'ch-191',
    title: '世界の街かど',
    description: '港町をあるく',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    startMin: 180,
    durationMin: 60,
    startLabel: '22:00',
    endLabel: '23:00',
  },
  {
    id: 'p016',
    channelId: 'ch-191',
    title: 'ETV 特集「記録する人々」',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    startMin: 240,
    durationMin: 120,
    startLabel: '23:00',
    endLabel: '01:00',
    subtitled: true,
  },
  {
    id: 'p017',
    channelId: 'ch-191',
    title: '深夜アニメ劇場',
    genre: 'anime',
    genreLabel: 'アニメ/特撮',
    startMin: 360,
    durationMin: 120,
    startLabel: '01:00',
    endLabel: '03:00',
  },
  {
    id: 'p018',
    channelId: 'ch-131',
    title: '夕方いちばん',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
    startMin: 0,
    durationMin: 30,
    startLabel: '19:00',
    endLabel: '19:30',
  },
  {
    id: 'p019',
    channelId: 'ch-131',
    title: '週末クイズ研究所',
    description: '新春スペシャルの予告編つき',
    genre: 'variety',
    genreLabel: 'バラエティ',
    startMin: 30,
    durationMin: 90,
    startLabel: '19:30',
    endLabel: '21:00',
  },
  {
    id: 'p020',
    channelId: 'ch-131',
    title: '夜ふかしラジオ倶楽部',
    description: '街で見つけた小さな話',
    genre: 'variety',
    genreLabel: 'バラエティ',
    startMin: 120,
    durationMin: 60,
    startLabel: '21:00',
    endLabel: '22:00',
  },
  {
    id: 'p021',
    channelId: 'ch-131',
    title: '水曜ドラマ「約束の丘」',
    description: '最終回',
    genre: 'drama',
    genreLabel: 'ドラマ',
    startMin: 180,
    durationMin: 60,
    startLabel: '22:00',
    endLabel: '23:00',
    subtitled: true,
  },
  {
    id: 'p022',
    channelId: 'ch-131',
    title: '深夜の商店街をあるく',
    description: 'シャッター街の日曜',
    genre: 'variety',
    genreLabel: 'バラエティ',
    startMin: 240,
    durationMin: 90,
    startLabel: '23:00',
    endLabel: '00:30',
  },
  {
    id: 'p023',
    channelId: 'ch-131',
    title: '深夜シネマ「遠い汽笛」',
    genre: 'movie',
    genreLabel: '映画',
    startMin: 330,
    durationMin: 150,
    startLabel: '00:30',
    endLabel: '03:00',
  },
  {
    id: 'p024',
    channelId: 'ch-181',
    title: '第一ニュース',
    genre: 'news',
    genreLabel: 'ニュース/報道',
    startMin: 0,
    durationMin: 60,
    startLabel: '19:00',
    endLabel: '20:00',
  },
  {
    id: 'p025',
    channelId: 'ch-181',
    title: '都市対抗クイズ選手権 準決勝',
    description: '近似値クイズと早押しの二本立て',
    genre: 'sports',
    genreLabel: 'スポーツ',
    startMin: 60,
    durationMin: 120,
    startLabel: '20:00',
    endLabel: '22:00',
  },
  {
    id: 'p026',
    channelId: 'ch-181',
    title: '金曜シネマ「星の渡り鳥」',
    description: '岬の観測小屋を舞台にしたひと夏の物語',
    detail:
      '渡り鳥の観測小屋を営む青年と、星の写真を撮りに来た旅人。ひと夏の岬を舞台に、去る者と残る者のすれ違いを描く劇場公開作をテレビ初放送。',
    genre: 'movie',
    genreLabel: '映画',
    startMin: 180,
    durationMin: 120,
    startLabel: '22:00',
    endLabel: '00:00',
    subtitled: true,
    booked: true,
  },
  {
    id: 'p027',
    channelId: 'ch-181',
    title: 'となりの発明王',
    genre: 'variety',
    genreLabel: 'バラエティ',
    startMin: 300,
    durationMin: 60,
    startLabel: '00:00',
    endLabel: '01:00',
  },
  {
    id: 'p028',
    channelId: 'ch-181',
    title: '夜のショッピング',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
    startMin: 360,
    durationMin: 120,
    startLabel: '01:00',
    endLabel: '03:00',
  },
  {
    id: 'p029',
    channelId: 'ch-171',
    title: '湾岸ワイド',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
    startMin: 0,
    durationMin: 60,
    startLabel: '19:00',
    endLabel: '20:00',
  },
  {
    id: 'p030',
    channelId: 'ch-171',
    title: '連続ドラマ「潮風の食卓」',
    description: '第3話',
    genre: 'drama',
    genreLabel: 'ドラマ',
    startMin: 60,
    durationMin: 60,
    startLabel: '20:00',
    endLabel: '21:00',
  },
  {
    id: 'p031',
    channelId: 'ch-171',
    title: '週末キッチンの手帖',
    description: '夏野菜の作り置き',
    genre: 'variety',
    genreLabel: 'バラエティ',
    startMin: 120,
    durationMin: 90,
    startLabel: '21:00',
    endLabel: '22:30',
  },
  {
    id: 'p032',
    channelId: 'ch-171',
    title: '情熱の現場',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    startMin: 210,
    durationMin: 60,
    startLabel: '22:30',
    endLabel: '23:30',
  },
  {
    id: 'p033',
    channelId: 'ch-171',
    title: 'ナイター中継 延長あり',
    description: '延長の可能性あり',
    genre: 'sports',
    genreLabel: 'スポーツ',
    startMin: 270,
    durationMin: 90,
    startLabel: '23:30',
    endLabel: '01:00',
    endUndecided: true,
  },
  {
    id: 'p034',
    channelId: 'ch-171',
    title: '通販の時間',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
    startMin: 360,
    durationMin: 120,
    startLabel: '01:00',
    endLabel: '03:00',
  },
  {
    id: 'p035',
    channelId: 'ch-161',
    title: 'コメット急行 #103',
    genre: 'anime',
    genreLabel: 'アニメ/特撮',
    startMin: 0,
    durationMin: 90,
    startLabel: '19:00',
    endLabel: '20:30',
    subtitled: true,
  },
  {
    id: 'p036',
    channelId: 'ch-161',
    title: 'ロボットくらぶ',
    genre: 'anime',
    genreLabel: 'アニメ/特撮',
    startMin: 90,
    durationMin: 60,
    startLabel: '20:30',
    endLabel: '21:30',
  },
  {
    id: 'p037',
    channelId: 'ch-161',
    title: '東都バラエティ',
    genre: 'variety',
    genreLabel: 'バラエティ',
    startMin: 150,
    durationMin: 60,
    startLabel: '21:30',
    endLabel: '22:30',
  },
  {
    id: 'p038',
    channelId: 'ch-161',
    title: '夜のドラマ「渡し船」',
    genre: 'drama',
    genreLabel: 'ドラマ',
    startMin: 210,
    durationMin: 90,
    startLabel: '22:30',
    endLabel: '00:00',
  },
  {
    id: 'p039',
    channelId: 'ch-161',
    title: '東都ニュース',
    genre: 'news',
    genreLabel: 'ニュース/報道',
    startMin: 300,
    durationMin: 60,
    startLabel: '00:00',
    endLabel: '01:00',
  },
  {
    id: 'p040',
    channelId: 'ch-161',
    title: '深夜アニメ枠',
    genre: 'anime',
    genreLabel: 'アニメ/特撮',
    startMin: 360,
    durationMin: 120,
    startLabel: '01:00',
    endLabel: '03:00',
  },
  {
    id: 'p041',
    channelId: 'ch-141',
    title: '夕方アニメ劇場',
    genre: 'anime',
    genreLabel: 'アニメ/特撮',
    startMin: 0,
    durationMin: 60,
    startLabel: '19:00',
    endLabel: '20:00',
  },
  {
    id: 'p042',
    channelId: 'ch-141',
    title: 'シティニュース',
    genre: 'news',
    genreLabel: 'ニュース/報道',
    startMin: 60,
    durationMin: 30,
    startLabel: '20:00',
    endLabel: '20:30',
  },
  {
    id: 'p043',
    channelId: 'ch-141',
    title: 'バスケットボール中継',
    genre: 'sports',
    genreLabel: 'スポーツ',
    startMin: 90,
    durationMin: 120,
    startLabel: '20:30',
    endLabel: '22:30',
  },
  {
    id: 'p044',
    channelId: 'ch-141',
    title: 'ライブハウスの夜',
    genre: 'music',
    genreLabel: '音楽',
    startMin: 210,
    durationMin: 60,
    startLabel: '22:30',
    endLabel: '23:30',
  },
  {
    id: 'p045',
    channelId: 'ch-141',
    title: 'アニメ「星の渡り鳥」外伝',
    genre: 'anime',
    genreLabel: 'アニメ/特撮',
    startMin: 270,
    durationMin: 90,
    startLabel: '23:30',
    endLabel: '01:00',
  },
  {
    id: 'p046',
    channelId: 'ch-141',
    title: '真夜中のトーク',
    genre: 'variety',
    genreLabel: 'バラエティ',
    startMin: 360,
    durationMin: 120,
    startLabel: '01:00',
    endLabel: '03:00',
  },
]
