import type { GuideDay } from '@/repository/programs'

/** The fixtures all sit on one day of the guide window. */
export const PROGRAM_DAY: GuideDay = {
  date: '2026-08-08',
  label: '8/8(金)',
  isToday: true,
}

/** Where "now" sits in the guide window, as minutes from its start. */
export const NOW_MIN = 124
export const NOW_LABEL = '21:04'

export const GUIDE_DAYS: GuideDay[] = [
  { date: '2026-08-07', label: '8/7(木)', isToday: false },
  PROGRAM_DAY,
  { date: '2026-08-09', label: '8/9(土)', isToday: false },
]

import {
  AERIAL_CHANNEL_FIXTURES,
  CHANNEL_FIXTURES,
} from '@/repository/channels.fixtures'
import type { Program, ProgramDetail } from '@/repository/programs'
import { withRelatedSettled } from '@/repository/programs'

export const PROGRAM_FIXTURES: Program[] = [
  {
    id: 'p001',
    channelId: 'ch-151',
    title: 'みなと ニュース7',
    description: '列島の記録的暑さ 夜間も熱中症に警戒を',
    genre: 'news',
    genreLabel: 'ニュース/報道',
    startMin: 0,
    durationMin: 60,
    startLabel: '19:00',
    endLabel: '20:00',
  },
  {
    id: 'p002',
    channelId: 'ch-151',
    title: 'くらしの窓口',
    description: '夏の停電にそなえる',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
    startMin: 60,
    durationMin: 30,
    startLabel: '20:00',
    endLabel: '20:30',
  },
  {
    id: 'p003',
    channelId: 'ch-151',
    title: 'ヘッドラインニュース',
    genre: 'news',
    genreLabel: 'ニュース/報道',
    startMin: 90,
    durationMin: 30,
    startLabel: '20:30',
    endLabel: '21:00',
  },
  {
    id: 'p004',
    channelId: 'ch-151',
    title: 'ニュースの視点9',
    description: '電力需給対策のポイントを担当記者が解説',
    genre: 'news',
    genreLabel: 'ニュース/報道',
    startMin: 120,
    durationMin: 60,
    startLabel: '21:00',
    endLabel: '22:00',
    subtitled: true,
  },
  {
    id: 'p005',
    channelId: 'ch-151',
    title: '土曜ドラマ「灯台のある町」',
    description: '第5話 帰ってきた同級生',
    genre: 'drama',
    genreLabel: 'ドラマ',
    startMin: 180,
    durationMin: 90,
    startLabel: '22:00',
    endLabel: '23:30',
  },
  {
    id: 'p006',
    channelId: 'ch-151',
    title: '手仕事の地図',
    description: '町工場の職人たち',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    startMin: 270,
    durationMin: 60,
    startLabel: '23:30',
    endLabel: '00:30',
  },
  {
    id: 'p007',
    channelId: 'ch-151',
    title: '深夜のニュース',
    genre: 'news',
    genreLabel: 'ニュース/報道',
    startMin: 330,
    durationMin: 30,
    startLabel: '00:30',
    endLabel: '01:00',
  },
  {
    id: 'p008',
    channelId: 'ch-151',
    title: '真夜中の音楽室',
    description: '夏の弦楽四重奏',
    genre: 'music',
    genreLabel: '音楽',
    startMin: 360,
    durationMin: 120,
    startLabel: '01:00',
    endLabel: '03:00',
  },
  /**
   * What a service that has split really carries: its own programmes for the
   * hours it has a second thing to show, and nothing at all in between. The
   * hours in between are not empty listings — they are the hours it is showing
   * what the whole service is showing, which the guide already has a column
   * for.
   */
  {
    id: 'p009',
    channelId: 'ch-152',
    title: '高校野球ダイジェスト',
    genre: 'sports',
    genreLabel: 'スポーツ',
    startMin: 0,
    durationMin: 120,
    startLabel: '19:00',
    endLabel: '21:00',
  },
  {
    id: 'p010',
    channelId: 'ch-152',
    title: 'データ気象台',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
    startMin: 210,
    durationMin: 60,
    startLabel: '22:30',
    endLabel: '23:30',
  },
  {
    id: 'p011',
    channelId: 'ch-152',
    title: '自然のしくみ 再放送',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    startMin: 420,
    durationMin: 50,
    startLabel: '02:00',
    endLabel: '02:50',
  },
  /**
   * The narrowest column the guide draws and the shortest cell it draws, in one
   * programme, carrying the longest genre name there is. Whatever a cell has to
   * give up when it runs out of room, it gives up here first.
   */
  {
    id: 'p047',
    channelId: 'ch-152',
    title: '五分間の科学',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    startMin: 470,
    durationMin: 10,
    startLabel: '02:50',
    endLabel: '03:00',
  },
  {
    id: 'p012',
    channelId: 'ch-191',
    title: 'はじめての天文学',
    description: '夏の大三角をさがす',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    startMin: 0,
    durationMin: 30,
    startLabel: '19:00',
    endLabel: '19:30',
  },
  {
    id: 'p013',
    channelId: 'ch-191',
    title: '手話ニュース',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
    startMin: 30,
    durationMin: 60,
    startLabel: '19:30',
    endLabel: '20:30',
  },
  {
    id: 'p014',
    channelId: 'ch-191',
    title: 'クラシックの時間',
    description: '夏の管弦楽',
    genre: 'music',
    genreLabel: '音楽',
    startMin: 90,
    durationMin: 90,
    startLabel: '20:30',
    endLabel: '22:00',
  },
  {
    id: 'p015',
    channelId: 'ch-191',
    title: '世界の街かど',
    description: '港町をあるく',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    startMin: 180,
    durationMin: 60,
    startLabel: '22:00',
    endLabel: '23:00',
  },
  {
    id: 'p016',
    channelId: 'ch-191',
    title: 'ETV 特集「記録する人々」',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    startMin: 240,
    durationMin: 120,
    startLabel: '23:00',
    endLabel: '01:00',
    subtitled: true,
  },
  {
    id: 'p017',
    channelId: 'ch-191',
    title: '深夜アニメ劇場',
    genre: 'anime',
    genreLabel: 'アニメ/特撮',
    startMin: 360,
    durationMin: 120,
    startLabel: '01:00',
    endLabel: '03:00',
  },
  {
    id: 'p018',
    channelId: 'ch-131',
    title: '夕方いちばん',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
    startMin: 0,
    durationMin: 30,
    startLabel: '19:00',
    endLabel: '19:30',
  },
  {
    id: 'p019',
    channelId: 'ch-131',
    title: '週末クイズ研究所',
    description: '新春スペシャルの予告編つき',
    genre: 'variety',
    genreLabel: 'バラエティ',
    startMin: 30,
    durationMin: 90,
    startLabel: '19:30',
    endLabel: '21:00',
  },
  {
    id: 'p020',
    channelId: 'ch-131',
    title: '夜ふかしラジオ倶楽部',
    description: '街で見つけた小さな話',
    genre: 'variety',
    genreLabel: 'バラエティ',
    startMin: 120,
    durationMin: 60,
    startLabel: '21:00',
    endLabel: '22:00',
  },
  {
    id: 'p021',
    channelId: 'ch-131',
    title: '水曜ドラマ「約束の丘」',
    description: '最終回',
    genre: 'drama',
    genreLabel: 'ドラマ',
    startMin: 180,
    durationMin: 60,
    startLabel: '22:00',
    endLabel: '23:00',
    subtitled: true,
  },
  {
    id: 'p022',
    channelId: 'ch-131',
    title: '深夜の商店街をあるく',
    description: 'シャッター街の日曜',
    genre: 'variety',
    genreLabel: 'バラエティ',
    startMin: 240,
    durationMin: 90,
    startLabel: '23:00',
    endLabel: '00:30',
  },
  {
    id: 'p023',
    channelId: 'ch-131',
    title: '深夜シネマ「遠い汽笛」',
    genre: 'movie',
    genreLabel: '映画',
    startMin: 330,
    durationMin: 150,
    startLabel: '00:30',
    endLabel: '03:00',
  },
  {
    id: 'p024',
    channelId: 'ch-181',
    title: '第一ニュース',
    genre: 'news',
    genreLabel: 'ニュース/報道',
    startMin: 0,
    durationMin: 60,
    startLabel: '19:00',
    endLabel: '20:00',
  },
  {
    id: 'p025',
    channelId: 'ch-181',
    title: '都市対抗クイズ選手権 準決勝',
    description: '近似値クイズと早押しの二本立て',
    genre: 'sports',
    genreLabel: 'スポーツ',
    startMin: 60,
    durationMin: 120,
    startLabel: '20:00',
    endLabel: '22:00',
  },
  {
    id: 'p026',
    channelId: 'ch-181',
    title: '金曜シネマ「星の渡り鳥」',
    description: '岬の観測小屋を舞台にしたひと夏の物語',
    genre: 'movie',
    genreLabel: '映画',
    startMin: 180,
    durationMin: 120,
    startLabel: '22:00',
    endLabel: '00:00',
    subtitled: true,
    booked: true,
    booking: {
      id: '2f6c1a90-8d47-4e15-b3c2-0a5e7d914b68',
      priority: 10,
      marginBeforeSeconds: 10,
      marginAfterSeconds: 30,
    },
  },
  {
    id: 'p027',
    channelId: 'ch-181',
    title: 'となりの発明王',
    genre: 'variety',
    genreLabel: 'バラエティ',
    startMin: 300,
    durationMin: 60,
    startLabel: '00:00',
    endLabel: '01:00',
  },
  {
    id: 'p028',
    channelId: 'ch-181',
    title: '夜のショッピング',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
    startMin: 360,
    durationMin: 120,
    startLabel: '01:00',
    endLabel: '03:00',
  },
  {
    id: 'p029',
    channelId: 'ch-171',
    title: '湾岸ワイド',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
    startMin: 0,
    durationMin: 60,
    startLabel: '19:00',
    endLabel: '20:00',
  },
  {
    id: 'p030',
    channelId: 'ch-171',
    title: '連続ドラマ「潮風の食卓」',
    description: '第3話',
    genre: 'drama',
    genreLabel: 'ドラマ',
    startMin: 60,
    durationMin: 60,
    startLabel: '20:00',
    endLabel: '21:00',
  },
  {
    id: 'p031',
    channelId: 'ch-171',
    title: '週末キッチンの手帖',
    description: '夏野菜の作り置き',
    genre: 'variety',
    genreLabel: 'バラエティ',
    startMin: 120,
    durationMin: 90,
    startLabel: '21:00',
    endLabel: '22:30',
  },
  {
    id: 'p032',
    channelId: 'ch-171',
    title: '情熱の現場',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    startMin: 210,
    durationMin: 60,
    startLabel: '22:30',
    endLabel: '23:30',
  },
  {
    id: 'p033',
    channelId: 'ch-171',
    title: 'ナイター中継 延長あり',
    description: '延長の可能性あり',
    genre: 'sports',
    genreLabel: 'スポーツ',
    startMin: 270,
    durationMin: 30,
    startLabel: '23:30',
    endLabel: '未定',
    endUndecided: true,
  },
  /**
   * A run of short programmes, the kind that fills the turn of the night. They
   * are what the smallest cell in the guide actually looks like: 10 to 20
   * minutes, so a tenth to a third of the height an hour is given.
   */
  {
    id: 'p048',
    channelId: 'ch-171',
    title: '深夜の気象情報',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
    startMin: 300,
    durationMin: 10,
    startLabel: '00:00',
    endLabel: '00:10',
  },
  {
    id: 'p049',
    channelId: 'ch-171',
    title: 'ミニ紀行 灯台のある町',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    startMin: 310,
    durationMin: 15,
    startLabel: '00:10',
    endLabel: '00:25',
  },
  {
    id: 'p050',
    channelId: 'ch-171',
    title: '深夜スポーツ',
    genre: 'sports',
    genreLabel: 'スポーツ',
    startMin: 325,
    durationMin: 20,
    startLabel: '00:25',
    endLabel: '00:45',
  },
  {
    id: 'p051',
    channelId: 'ch-171',
    title: 'ショートアニメ さかなの街',
    genre: 'anime',
    genreLabel: 'アニメ/特撮',
    startMin: 345,
    durationMin: 15,
    startLabel: '00:45',
    endLabel: '01:00',
  },
  {
    id: 'p034',
    channelId: 'ch-171',
    title: '通販の時間',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
    startMin: 360,
    durationMin: 120,
    startLabel: '01:00',
    endLabel: '03:00',
  },
  {
    id: 'p035',
    channelId: 'ch-161',
    title: 'コメット急行 #103',
    genre: 'anime',
    genreLabel: 'アニメ/特撮',
    startMin: 0,
    durationMin: 90,
    startLabel: '19:00',
    endLabel: '20:30',
    subtitled: true,
  },
  {
    id: 'p036',
    channelId: 'ch-161',
    title: 'ロボットくらぶ',
    genre: 'anime',
    genreLabel: 'アニメ/特撮',
    startMin: 90,
    durationMin: 60,
    startLabel: '20:30',
    endLabel: '21:30',
  },
  {
    id: 'p037',
    channelId: 'ch-161',
    title: '東都バラエティ',
    genre: 'variety',
    genreLabel: 'バラエティ',
    startMin: 150,
    durationMin: 60,
    startLabel: '21:30',
    endLabel: '22:30',
  },
  {
    id: 'p038',
    channelId: 'ch-161',
    title: '夜のドラマ「渡し船」',
    genre: 'drama',
    genreLabel: 'ドラマ',
    startMin: 210,
    durationMin: 90,
    startLabel: '22:30',
    endLabel: '00:00',
  },
  {
    id: 'p039',
    channelId: 'ch-161',
    title: '東都ニュース',
    genre: 'news',
    genreLabel: 'ニュース/報道',
    startMin: 300,
    durationMin: 60,
    startLabel: '00:00',
    endLabel: '01:00',
  },
  {
    id: 'p040',
    channelId: 'ch-161',
    title: '深夜アニメ枠',
    genre: 'anime',
    genreLabel: 'アニメ/特撮',
    startMin: 360,
    durationMin: 120,
    startLabel: '01:00',
    endLabel: '03:00',
  },
  {
    id: 'p041',
    channelId: 'ch-141',
    title: '夕方アニメ劇場',
    genre: 'anime',
    genreLabel: 'アニメ/特撮',
    startMin: 0,
    durationMin: 60,
    startLabel: '19:00',
    endLabel: '20:00',
  },
  {
    id: 'p042',
    channelId: 'ch-141',
    title: 'シティニュース',
    genre: 'news',
    genreLabel: 'ニュース/報道',
    startMin: 60,
    durationMin: 30,
    startLabel: '20:00',
    endLabel: '20:30',
  },
  {
    id: 'p043',
    channelId: 'ch-141',
    title: 'バスケットボール中継',
    genre: 'sports',
    genreLabel: 'スポーツ',
    startMin: 90,
    durationMin: 120,
    startLabel: '20:30',
    endLabel: '22:30',
  },
  {
    id: 'p044',
    channelId: 'ch-141',
    title: 'ライブハウスの夜',
    genre: 'music',
    genreLabel: '音楽',
    startMin: 210,
    durationMin: 60,
    startLabel: '22:30',
    endLabel: '23:30',
  },
  {
    id: 'p045',
    channelId: 'ch-141',
    title: 'アニメ「星の渡り鳥」外伝',
    genre: 'anime',
    genreLabel: 'アニメ/特撮',
    startMin: 270,
    durationMin: 90,
    startLabel: '23:30',
    endLabel: '01:00',
  },
  {
    id: 'p046',
    channelId: 'ch-141',
    title: '真夜中のトーク',
    genre: 'variety',
    genreLabel: 'バラエティ',
    startMin: 360,
    durationMin: 120,
    startLabel: '01:00',
    endLabel: '03:00',
  },
]

/**
 * A programme in every column of the full line-up, so that a grid drawn at
 * that scale is asked to hold something readable rather than nineteen empty
 * columns. The eight services the programmes above were written for are dealt
 * round the rest of it — main services onto main services and the split one
 * onto the split ones, so that a narrow column gets what a narrow column gets.
 */
export const AERIAL_PROGRAM_FIXTURES: Program[] =
  AERIAL_CHANNEL_FIXTURES.flatMap((channel, index) => {
    const sources = CHANNEL_FIXTURES.filter(
      (source) => Boolean(source.sub) === Boolean(channel.sub),
    )
    const source = sources[index % sources.length]

    return PROGRAM_FIXTURES.filter(
      (program) => program.channelId === source.id,
    ).map((program) => ({
      ...program,
      id: `${program.id}-${channel.id}`,
      channelId: channel.id,
    }))
  })

export const PROGRAM_DETAIL_FIXTURES: Record<
  'standard' | 'relayed' | 'simulcast' | 'undecided' | 'minimal' | 'multiline',
  ProgramDetail
> = {
  standard: {
    program: {
      id: '33221-1521-40613',
      channelId: 'ch-151',
      title: '第58回 全都選抜クイズ選手権 決勝🈑',
      description:
        '海浜公園アリーナから決勝の模様を生中継。全 128 校の頂点をかけて、早押しと近似値クイズの二本立てで争う。',
      genre: 'variety',
      genreLabel: 'バラエティ',
      startMin: 120,
      durationMin: 145,
      startLabel: '21:00',
      endLabel: '23:25',
      subtitled: true,
    },
    day: PROGRAM_DAY,
    channel: CHANNEL_FIXTURES[0],
    items: [
      {
        heading: '番組内容',
        text: '【解説】川田 このみ\n【アナウンサー】津島 陽\n決勝は 3 回戦制。第 1 回戦は各校 2 名による早押し、第 2 回戦は近似値、最終回戦は代表 1 名の一騎打ちで勝敗を決める。',
      },
      {
        heading: '出演者',
        text: '【司会】田無 千秋\n【ゲスト】前回優勝校のみなさん',
      },
    ],
    related: [],
    durationLabel: '2時間25分',
  },
  relayed: {
    program: {
      id: '33221-1521-40621',
      channelId: 'ch-151',
      title: '第58回 全都選抜クイズ選手権 準決勝 第二試合🈑',
      description:
        '海浜公園アリーナから準決勝の第二試合を中継。試合の展開によっては放送時間を延長してお伝えします。',
      genre: 'variety',
      genreLabel: 'バラエティ',
      startMin: 0,
      durationMin: 120,
      startLabel: '19:00',
      endLabel: '21:00',
      subtitled: true,
    },
    day: PROGRAM_DAY,
    channel: CHANNEL_FIXTURES[0],
    items: [
      {
        heading: '番組内容',
        text: '準決勝屈指の接戦が予想される一戦。前の試合で全問正答を記録した常連校と、無敗で勝ち上がった初出場校が激突する。',
      },
    ],
    related: withRelatedSettled(
      [
        {
          key: '33221-1531-40622',
          kind: 'relayed',
          channelLabel: '191 みなと教育1',
        },
        { key: '33251-1541-40623', kind: 'shared' },
      ],
      CHANNEL_FIXTURES[0],
    ),
    durationLabel: '2時間',
  },
  simulcast: {
    program: {
      id: '33221-1521-40641',
      channelId: 'ch-151',
      title: 'みなと ニュース7🈑',
      description:
        '列島の記録的暑さと各地の備えを 30 分でまとめてお伝えします。',
      genre: 'news',
      genreLabel: 'ニュース/報道',
      startMin: 0,
      durationMin: 30,
      startLabel: '19:00',
      endLabel: '19:30',
      subtitled: true,
    },
    day: PROGRAM_DAY,
    channel: CHANNEL_FIXTURES[0],
    items: [
      {
        heading: '出演者',
        text: '【キャスター】小坂 玲\n【気象キャスター】木戸 真幸',
      },
    ],
    related: withRelatedSettled(
      [
        {
          key: '33221-1522-40641',
          kind: 'shared',
          channelLabel: '151 みなと総合1',
        },
        {
          key: '33221-1523-40641',
          kind: 'shared',
          channelLabel: '151 みなと総合1',
        },
        {
          key: '33251-1541-40641',
          kind: 'shared',
          channelLabel: '181 第一テレビ1',
        },
        {
          key: '33251-1542-40641',
          kind: 'shared',
          channelLabel: '181 第一テレビ1',
        },
      ],
      CHANNEL_FIXTURES[0],
    ),
    durationLabel: '30分',
  },
  undecided: {
    program: {
      id: '33241-1561-40711',
      channelId: 'ch-171',
      title: 'プロ野球「湾岸マリンズ×東都スターズ」',
      description: '本拠地スタジアムから第 18 回戦を実況生中継。',
      genre: 'sports',
      genreLabel: 'スポーツ',
      startMin: 270,
      durationMin: 30,
      startLabel: '23:30',
      endLabel: '未定',
      endUndecided: true,
    },
    day: PROGRAM_DAY,
    channel: CHANNEL_FIXTURES[5],
    items: [
      {
        heading: '出演者',
        text: '【実況】三崎 高志\n【解説】元監督 浜口 剛',
      },
    ],
    related: [],
  },
  multiline: {
    program: {
      id: '33221-1521-40615',
      channelId: 'ch-151',
      title: '入り江のアトリエ 夏の三日間🈑',
      description:
        '入り江の小さな工房を三日にわたってたずねる。\n初日は道具の手入れ、二日目は窯入れ、最終日は仕上げまでを追う。\n\n※天候により内容を変更する場合があります。',
      genre: 'doc',
      genreLabel: 'ドキュメンタリー/教養',
      startMin: 0,
      durationMin: 75,
      startLabel: '19:00',
      endLabel: '20:15',
      subtitled: true,
    },
    day: PROGRAM_DAY,
    channel: CHANNEL_FIXTURES[0],
    items: [
      {
        heading: '番組内容',
        text: '一日目  道具の手入れ\n二日目  窯入れと火の番\n三日目  仕上げと搬出\n\n工房の主が四十年つづけてきた手順を、季節の道具とともにたどる。',
      },
      {
        heading: '出演者',
        text: '【語り】  相原 みどり\n【出演】  柏木 泉',
      },
    ],
    related: [],
    durationLabel: '1時間15分',
  },
  minimal: {
    program: {
      id: '33261-1571-40801',
      channelId: 'ch-141',
      title: '夜のショッピング',
      genre: 'info',
      genreLabel: '情報/ワイドショー',
      startMin: 360,
      durationMin: 60,
      startLabel: '01:00',
      endLabel: '02:00',
    },
    day: PROGRAM_DAY,
    channel: CHANNEL_FIXTURES[7],
    items: [],
    related: [],
    durationLabel: '1時間',
  },
}
