import type { Route } from 'next'

import type { QualityResult, QualityThreshold } from '@/repository/quality'

const WINDOWS = [
  { label: '24 時間', days: 1 },
  { label: '7 日', days: 7 },
  { label: '30 日', days: 30 },
]

const windows = (current: string) =>
  WINDOWS.map((one) => ({
    label: one.label,
    href: `/settings/quality?days=${one.days}` as Route,
    current: one.label === current,
  }))

const THRESHOLDS: QualityThreshold[] = [
  {
    key: 'packetsLostWarning',
    label: 'ドロップ率の警告水準',
    value: '0.02%',
    basis: '既定 0.02% · 根拠 4,320 件',
    shipped: '0.02%',
    provisional: true,
    amount: '0.02',
    unit: '%',
    lowest: 0,
    highest: 100,
  },
  {
    key: 'packetsLostUnwatchable',
    label: 'ドロップ率の視聴不可の恐れ',
    value: '0.1%',
    basis: '既定 0.1% · 根拠 4,320 件',
    shipped: '0.1%',
    provisional: true,
    amount: '0.1',
    unit: '%',
    lowest: 0,
    highest: 100,
  },
  {
    key: 'packetsLeftScrambled',
    label: 'スクランブル残存率の上限',
    value: '0.05%',
    basis: '既定 0.05% · 根拠 4,320 件',
    shipped: '0.05%',
    provisional: true,
    amount: '0.05',
    unit: '%',
    lowest: 0,
    highest: 100,
  },
  {
    key: 'overflows',
    label: '取りこぼしの上限',
    value: '1回',
    basis: '既定 1回 · 根拠 4,320 件',
    shipped: '1回',
    provisional: true,
    amount: '1',
    unit: '回',
    lowest: 0,
    highest: 1000000,
  },
  {
    key: 'lockRate',
    label: 'lock 率の下限',
    value: '99%',
    basis: '既定 99% · 根拠 0 件',
    shipped: '99%',
    provisional: true,
    amount: '99',
    unit: '%',
    lowest: 0,
    highest: 100,
  },
  {
    key: 'carrierToNoiseFloor',
    label: 'CNR の下限',
    value: '15dB',
    basis: '既定 15dB · 根拠 0 件',
    shipped: '15dB',
    provisional: true,
    amount: '15',
    unit: 'dB',
    lowest: -100,
    highest: 100,
  },
  {
    key: 'bitErrorRateCeiling',
    label: 'post-Viterbi ビット誤り率の上限',
    value: '1.0e-4',
    basis: '既定 1.0e-4 · 根拠 0 件',
    shipped: '1.0e-4',
    provisional: true,
    amount: '0.0001',
    unit: '',
    lowest: 0,
    highest: 1,
  },
  {
    key: 'supplySilence',
    label: '供給途絶の判定',
    value: '5分',
    basis: '既定 5分 · 根拠 0 件',
    shipped: '5分',
    provisional: true,
    amount: '5',
    unit: '分',
    lowest: 0.016666,
    highest: 1440,
  },
]

const NOT_SAMPLED = { level: 'unmeasured' } as const

export const QUALITY: QualityResult = {
  windows: windows('24 時間'),
  stats: [
    {
      key: 'drop',
      label: '直近 24 時間のドロップ率',
      value: '0.021',
      unit: '%',
      level: 'warn',
      levelLabel: '警告水準',
      aside: '閾値は暫定',
      foot: '録画 14 本 / うち未計測 3 本',
    },
    {
      key: 'problem',
      label: '問題のある録画',
      value: '2',
      unit: '件',
      level: 'bad',
      levelLabel: '視聴不可の恐れ',
      link: { href: '/library', label: 'ライブラリで絞り込む' },
    },
    {
      key: 'scramble',
      label: 'スクランブル残存率',
      value: '0.000',
      unit: '%',
      level: 'good',
      levelLabel: '良好',
      aside: '録画 11 本を計測',
    },
    {
      key: 'health',
      label: 'チューナーヘルス',
      value: '3 / 4',
      unit: '健全',
      link: { href: '/settings/tuners', label: 'チューナーへ' },
      foot: '信号品質 未計測',
    },
  ],
  thresholds: THRESHOLDS,
  warnMarkPct: 20,
  channels: [
    {
      id: '32736-1024',
      name: 'みなと総合1',
      no: '151',
      dropRate: '0.152%',
      barPct: 100,
      level: 'bad',
      note: '録画 2 本を計測',
    },
    {
      id: '32737-1032',
      name: '中央テレビ1',
      no: '131',
      dropRate: '0.031%',
      barPct: 31,
      level: 'warn',
      note: '録画 1 本を計測',
    },
    {
      id: '32738-1040',
      name: 'みなと教育1',
      no: '191',
      dropRate: '0.002%',
      barPct: 2,
      level: 'good',
      note: '録画 3 本を計測',
    },
    {
      id: '32739-1048',
      name: '東都テレビ1',
      no: '161',
      dropRate: '0.003%',
      barPct: 3,
      level: 'good',
      note: '録画 2 本を計測',
    },
    {
      id: '32740-1056',
      name: '湾岸放送1',
      no: '171',
      dropRate: '0.002%',
      barPct: 2,
      level: 'good',
      note: '録画 2 本を計測',
    },
    {
      id: '32741-1064',
      name: '第一テレビ1',
      no: '181',
      dropRate: '0.006%',
      barPct: 6,
      level: 'good',
      note: '録画 1 本を計測',
    },
    {
      id: '32742-1072',
      name: 'シティ MX1',
      no: '141',
      level: 'unmeasured',
      note: '録画 3 本 / うち未計測 3 本',
    },
  ],
  satellites: [],
  tuners: [
    {
      id: 'adapter1.frontend0',
      device: 'adapter1.frontend0',
      hardware: '録画 9 本を計測',
      state: { level: 'good', label: '健全' },
      drop: { value: '0.002', unit: '%', level: 'good' },
      lock: NOT_SAMPLED,
      cnr: NOT_SAMPLED,
      ber: NOT_SAMPLED,
    },
    {
      id: 'adapter1.frontend1',
      device: 'adapter1.frontend1',
      hardware: '録画 4 本を計測',
      state: { level: 'good', label: '健全' },
      drop: { value: '0.001', unit: '%', level: 'good' },
      lock: NOT_SAMPLED,
      cnr: NOT_SAMPLED,
      ber: NOT_SAMPLED,
    },
    {
      id: 'adapter3.frontend0',
      device: 'adapter3.frontend0',
      hardware: '録画 2 本を計測',
      state: { level: 'bad', label: '視聴不可の恐れ' },
      drop: { value: '0.152', unit: '%', level: 'bad' },
      lock: NOT_SAMPLED,
      cnr: NOT_SAMPLED,
      ber: NOT_SAMPLED,
    },
    {
      id: 'adapter3.frontend1',
      device: 'adapter3.frontend1',
      hardware: '録画 3 本 / うち未計測 3 本',
      state: { level: 'unmeasured', label: '未計測' },
      drop: NOT_SAMPLED,
      lock: NOT_SAMPLED,
      cnr: NOT_SAMPLED,
      ber: NOT_SAMPLED,
    },
  ],
  problemRecordings: [
    {
      id: 'rec-1',
      title: 'みなと ニュース7',
      where: 'みなと総合1 · 08/09 21:00',
      drops: 'ドロップ 3,842',
      pct: '0.152%',
      level: 'bad',
    },
    {
      id: 'rec-2',
      title: '夕方いちばん',
      where: '中央テレビ1 · 08/10 08:15',
      drops: 'ドロップ 812',
      pct: '0.031%',
      level: 'warn',
    },
  ],
}

export const NOTHING_MEASURED: QualityResult = {
  windows: windows('30 日'),
  stats: [
    {
      key: 'drop',
      label: '直近 30 日のドロップ率',
      level: 'unmeasured',
      levelLabel: '未計測',
      aside: '閾値は暫定',
      foot: '録画 0 本',
    },
    {
      key: 'problem',
      label: '問題のある録画',
      value: '0',
      unit: '件',
      link: { href: '/library', label: 'ライブラリで絞り込む' },
    },
    {
      key: 'scramble',
      label: 'スクランブル残存率',
      level: 'unmeasured',
      levelLabel: '未計測',
      aside: '録画 0 本',
    },
    {
      key: 'health',
      label: 'チューナーヘルス',
      level: 'nodata',
      levelLabel: '対象なし',
      link: { href: '/settings/tuners', label: 'チューナーへ' },
      foot: '信号品質 未計測',
    },
  ],
  thresholds: THRESHOLDS.map((one) => ({
    ...one,
    basis: one.basis.replace(/根拠 [\d,]+ 件/, '根拠 0 件'),
  })),
  warnMarkPct: 20,
  channels: [],
  satellites: [],
  tuners: [],
  problemRecordings: [],
}

export const MORE_TUNERS_THAN_FIT: QualityResult = {
  ...QUALITY,
  tuners: Array.from({ length: 24 }, (_, index) => {
    const device = `adapter${Math.floor(index / 2) + 1}.frontend${index % 2}`

    return {
      ...QUALITY.tuners[index % QUALITY.tuners.length],
      id: device,
      device,
    }
  }),
}
