import type { GuideChannel } from '@/repository/programs'
import type { SearchHit } from '@/repository/search'

export const SEARCH_HIT_FIXTURES: SearchHit[] = [
  {
    id: '131-1310-40001',
    channelName: 'みなと総合1',
    channelNo: '151',
    dayLabel: '8/9(土)',
    startLabel: '19:30',
    endLabel: '20:15',
    endUndecided: false,
    title: '空から見る港町の夏',
    description: '上空からたどる岬と灯台 ひと夏の記録',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    booked: true,
  },
  {
    id: '131-1310-40002',
    channelName: '中央テレビ1',
    channelNo: '131',
    dayLabel: '8/9(土)',
    startLabel: '21:00',
    endLabel: '23:09',
    endUndecided: false,
    title: '土曜シネマ「砂浜の観測所」',
    description: '海辺の観測所に集う人々のひと夏を描く長編',
    genre: 'movie',
    genreLabel: '映画',
  },
  {
    id: '131-1310-40003',
    channelName: 'シティ MX1',
    channelNo: '141',
    dayLabel: '8/10(日)',
    startLabel: '00:30',
    endLabel: '01:00',
    endUndecided: false,
    title: '真夜中の水槽通信',
    description: '夜の水族館で出会う小さな生きものたち',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
  },
  {
    id: '131-1310-40004',
    channelName: '湾岸放送1',
    channelNo: '171',
    dayLabel: '8/10(日)',
    startLabel: '18:00',
    endLabel: '18:54',
    endUndecided: false,
    title: '渓谷さんぽ 夏の吊り橋',
    description: '滝つぼと渡し船 涼を求めて谷をゆく',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    booked: true,
  },
  {
    id: '131-1310-40005',
    channelName: '第一テレビ1',
    channelNo: '181',
    dayLabel: '8/10(日)',
    startLabel: '21:00',
    endLabel: '22:54',
    endUndecided: false,
    title: '日曜スペシャル 島の観測日誌',
    description: '無人島の測候所を守る夫婦の一年',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
  },
  {
    id: '131-1310-40006',
    channelName: 'みなと教育1',
    channelNo: '191',
    dayLabel: '8/10(日)',
    startLabel: '22:00',
    endLabel: '22:45',
    endUndecided: false,
    title: '手仕事の図鑑「櫓をつくる」',
    description: '祭りの櫓を組む職人たちの夏',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
  },
  {
    id: '131-1310-40007',
    channelName: '東都テレビ1',
    channelNo: '161',
    dayLabel: '8/11(月)',
    startLabel: '20:00',
    endLabel: '21:54',
    endUndecided: false,
    title: '終着駅の食堂車',
    description: '一日三本の路線と山あいの食堂をめぐる',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
  },
  {
    id: '131-1310-40008',
    channelName: 'シティ MX1',
    channelNo: '141',
    dayLabel: '8/11(月)',
    startLabel: '21:00',
    endLabel: '22:54',
    endUndecided: false,
    title: '映画「橋の下のプラネタリウム」',
    description: '高架下の小さな投影機がつなぐ、ひと夏の物語',
    genre: 'movie',
    genreLabel: '映画',
  },
  {
    id: '131-1310-40009',
    channelName: 'みなと総合1',
    channelNo: '151',
    dayLabel: '8/11(月)',
    startLabel: '22:00',
    endLabel: '22:50',
    endUndecided: false,
    title: '灯台守の朝ごはん',
    description: '岬に暮らす一家の、いちばん短い夏',
    genre: 'info',
    genreLabel: '情報/ワイドショー',
  },
  {
    id: '131-1310-40010',
    channelName: 'みなと教育1',
    channelNo: '191',
    dayLabel: '8/12(火)',
    startLabel: '21:00',
    endLabel: '21:30',
    endUndecided: false,
    title: '空撮紀行 夏の海岸線',
    description: '白い灯台と入り江をたどる30分',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
  },
  {
    id: '131-1310-40011',
    channelName: '第一テレビ1',
    channelNo: '181',
    dayLabel: '8/12(火)',
    startLabel: '23:15',
    endLabel: '00:10',
    endUndecided: false,
    title: '深夜の甲板食堂',
    description: 'フェリーの厨房で生まれる一皿を追う',
    genre: 'variety',
    genreLabel: 'バラエティ',
  },
  {
    id: '131-1310-40012',
    channelName: '中央テレビ1',
    channelNo: '131',
    dayLabel: '8/13(水)',
    startLabel: '19:00',
    endLabel: '20:54',
    endUndecided: false,
    title: '果ての岬 紀行スペシャル',
    description: '地の果ての岬と溶けはじめた氷河をめぐる',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
  },
  {
    id: '131-1310-40013',
    channelName: '湾岸放送1',
    channelNo: '171',
    dayLabel: '8/13(水)',
    startLabel: '21:00',
    endLabel: '22:54',
    endUndecided: false,
    title: '水曜シネマ「遠泳の夜」',
    description: '海辺の町を舞台にした再会の物語',
    genre: 'movie',
    genreLabel: '映画',
  },
  {
    id: '131-1310-40014',
    channelName: '東都テレビ1',
    channelNo: '161',
    dayLabel: '8/14(木)',
    startLabel: '19:00',
    endLabel: '20:54',
    endUndecided: false,
    title: '町工場の飛行日誌',
    description: '模型飛行機に懸ける三代の夏',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
    booked: true,
  },
  {
    id: '131-1310-40015',
    channelName: 'シティ MX1',
    channelNo: '141',
    dayLabel: '8/14(木)',
    startLabel: '22:00',
    endLabel: '22:30',
    endUndecided: false,
    title: 'アニメ「浮き桟橋のなつやすみ」',
    description: '#6 花火と忘れもの',
    genre: 'anime',
    genreLabel: 'アニメ/特撮',
  },
  {
    id: '131-1310-40016',
    channelName: 'みなと総合1',
    channelNo: '151',
    dayLabel: '8/15(金)',
    startLabel: '19:30',
    endLabel: '20:15',
    endUndecided: false,
    title: '湿原さんぽ 霧の朝',
    description: '早朝の湿原と、そこで暮らす生きものたち',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
  },
  {
    id: '131-1310-40017',
    channelName: '中央テレビ1',
    channelNo: '131',
    dayLabel: '8/15(金)',
    startLabel: '21:00',
    endLabel: '22:50',
    endUndecided: false,
    title: '映画「汽笛が消える前に」',
    description: '廃線最後の夏を見送る少年たちの記録',
    genre: 'movie',
    genreLabel: '映画',
  },
  {
    id: '131-1310-40018',
    channelName: 'みなと教育1',
    channelNo: '191',
    dayLabel: '8/15(金)',
    startLabel: '22:00',
    endLabel: '22:45',
    endUndecided: false,
    title: '棚田をつくる人々',
    description: '石積みを守る集落の一年をたどる',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
  },
  {
    id: '131-1310-40019',
    channelName: '第一テレビ1',
    channelNo: '181',
    dayLabel: '8/16(土)',
    startLabel: '01:20',
    endLabel: '01:50',
    endUndecided: false,
    title: '石畳の街道をあるく',
    description: '真夏の光が射す旧街道を行く',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
  },
  {
    id: '131-1310-40020',
    channelName: '湾岸放送1',
    channelNo: '171',
    dayLabel: '8/17(日)',
    startLabel: '02:00',
    endUndecided: true,
    title: '夜どおし天体中継 夏の流星群',
    description: '峠の観測所から朝まで生中継',
    genre: 'doc',
    genreLabel: 'ドキュメンタリー/教養',
  },
]

export const SEARCH_CHANNEL_FIXTURES: GuideChannel[] = [
  { no: '131', name: '中央テレビ1', networkId: 131 },
  { no: '141', name: 'シティ MX1', networkId: 141 },
  { no: '151', name: 'みなと総合1', networkId: 151 },
  { no: '161', name: '東都テレビ1', networkId: 161 },
  { no: '171', name: '湾岸放送1', networkId: 171 },
  { no: '181', name: '第一テレビ1', networkId: 181 },
  { no: '191', name: 'みなと教育1', networkId: 191 },
].map((carried, index) => ({
  id: `${carried.networkId}-${1310 + index}`,
  no: carried.no,
  name: carried.name,
  kind: 'terrestrial' as const,
  networkId: carried.networkId,
  serviceId: 1310 + index,
  sortKey: [Number(carried.no), carried.networkId, 1310 + index] as [
    number,
    number,
    number,
  ],
}))
