import type { ChannelsResult, TunerResult } from '@/repository/tuners'

export const TUNERS: TunerResult = {
  instanceId: 'b7f2c9',
  notices: [
    {
      tone: 'danger',
      body: '1台のチューナーが利用できません。adapter2 — 設定の種別(地上波)と検出結果(衛星)が一致しません。',
      actions: [{ label: '該当行へ', href: '#adapter2' }],
    },
    {
      tone: 'warn',
      body: '保存済み・未反映の変更があります。反映には driver の再起動が必要です。録画が 1 件進行中のため、まだ再起動できません。みなと総合1 27ch の終了予定は 21:15 です。',
      actions: [
        { label: '変更内容を確認' },
        { label: 'driver を再起動', control: 'button', disabled: true },
      ],
    },
  ],
  thresholdHours: 24,
  rows: [
    {
      id: 'adapter1',
      device: 'adapter1',
      hardware: 'PT3 / frontend0',
      kind: '地上波',
      enabled: true,
      session: {
        label: '録画',
        tone: 'recording',
        service: 'みなと総合1',
        code: '27ch',
      },
      state: 'ok',
      stateLabel: '正常',
      lastService: { at: '08/07 20:58', ago: '6 分前' },
    },
    {
      id: 'adapter3',
      device: 'adapter3',
      hardware: 'PT3 / frontend0',
      kind: '地上波',
      enabled: false,
      draining: true,
      session: { label: 'EPG 収集', tone: 'epg', code: 'TS 32737 (21ch)' },
      state: 'ok',
      stateLabel: '正常',
      lastService: { at: '08/07 20:40', ago: '24 分前' },
    },
    {
      id: 'adapter0',
      device: 'adapter0',
      hardware: 'PT3 / frontend0',
      kind: '衛星',
      enabled: true,
      idleLabel: 'アイドル',
      state: 'warn',
      stateLabel: '警告',
      stateSub: 'BS のサービスが 26 時間 0 件',
      lastService: { at: '08/06 19:02', ago: '26 時間前' },
      lnb: 'オフ(既定)',
    },
    {
      id: 'adapter2',
      device: 'adapter2',
      hardware: 'PT3 / frontend0',
      kind: '地上波',
      kindUnsure: true,
      enabled: true,
      idleLabel: '割当停止中',
      state: 'faulted',
      stateLabel: '種別不一致',
      stateSub: '設定: 地上波 / 検出: 衛星',
      lnb: 'オフ(既定)',
    },
  ],
  detectionDiff: [
    {
      kind: 'add',
      tag: '新規',
      device: 'adapter4 — PX-W3U4(地上波)',
      note: '保存後に有効化できます',
    },
    {
      kind: 'del',
      tag: '消失',
      device: 'adapter2 — PT3(衛星)',
      note: '一覧からは削除されず「消失」表示になります',
    },
  ],
}

export const CHANNEL_SCAN: ChannelsResult = {
  warning: {
    body: 'BS のサービスが 0 件です(連続 26 時間)。有効な候補チャンネルを持つサービスがひとつも確認できていません。',
    actions: [{ label: '切り分けを見る', href: '/settings/quality' }],
  },
  lastScan: '前回: 地上波 50ch / 6分32秒 · 08/05 03:00',
  groups: [
    {
      kind: '地上波',
      stat: '8 サービス / 6 TS(TV 6 · ワンセグ 1 · データ 1)',
      services: [
        {
          id: 's-151',
          name: 'みなと総合1',
          sid: 'sid 1024',
          kind: 'TV',
          currentCh: '27ch',
          candidates: 2,
          needsCheck: 1,
          enabled: true,
          lastSeen: '21:04',
        },
        {
          id: 's-152',
          name: 'みなと総合2',
          sid: 'sid 1025',
          kind: 'ワンセグ',
          currentCh: '27ch',
          candidates: 1,
          needsCheck: 0,
          enabled: true,
          lastSeen: '21:04',
        },
        {
          id: 's-191',
          name: 'みなと教育1',
          sid: 'sid 1032',
          kind: 'TV',
          currentCh: '26ch',
          candidates: 1,
          needsCheck: 0,
          enabled: true,
          lastSeen: '21:00',
        },
        {
          id: 's-131',
          name: '中央テレビ1',
          sid: 'sid 1040',
          kind: 'TV',
          currentCh: '25ch',
          candidates: 1,
          needsCheck: 0,
          enabled: true,
          lastSeen: '21:02',
        },
        {
          id: 's-181',
          name: '第一テレビ1',
          sid: 'sid 1048',
          kind: 'TV',
          currentCh: '24ch',
          candidates: 2,
          needsCheck: 0,
          enabled: true,
          lastSeen: '20:59',
        },
        {
          id: 's-171',
          name: '湾岸放送1',
          sid: 'sid 1056',
          kind: 'TV',
          currentCh: '22ch',
          candidates: 1,
          needsCheck: 0,
          enabled: true,
          lastSeen: '21:01',
        },
        {
          id: 's-161',
          name: '東都テレビ1',
          sid: 'sid 1064',
          kind: 'TV',
          currentCh: '23ch',
          candidates: 1,
          needsCheck: 0,
          enabled: true,
          lastSeen: '21:03',
        },
        {
          id: 's-141',
          name: 'シティ MX1',
          sid: 'sid 1072',
          kind: 'TV',
          currentCh: '21ch',
          candidates: 1,
          needsCheck: 0,
          enabled: false,
          lastSeen: '3 日前',
        },
      ],
    },
    { kind: 'BS', stat: '0 サービス', services: [] },
  ],
}
