/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/tuners/detected': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getDetectedTuners']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tuners': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getTuners']
    put: operations['putTuners']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tuners/{deviceId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['patchTuner']
    trace?: never
  }
  '/api/services/{networkId}-{serviceId}/candidate-channels': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['addCandidateChannel']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/services/{networkId}-{serviceId}/candidate-channels/{candidateChannelId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: operations['deleteCandidateChannel']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/services/{networkId}-{serviceId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getService']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/services': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listServices']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/services/{networkId}-{serviceId}/selected-channel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['putSelectedChannel']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tuners/scan/{scanId}/apply': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['applyScan']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tuners/scan/{scanId}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['cancelScan']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tuners/scan/{scanId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getScan']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tuners/scan-runs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listScanRuns']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tuners/scan': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['startScan']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/epg/collect-now': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['collectNow']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/epg/archive/forget-service': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['forgetArchivedService']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/epg/collection-status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getCollectionStatus']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/programs/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getProgramme']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/programs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getProgrammeGuide']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/epg/rebuild': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['rebuildEpg']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/programs/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['searchProgrammes']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/driver/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getDriverStatus']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/driver/restart': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['restartDriver']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['changePassword']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/sessions/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: operations['deleteSession']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getMe']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/oidc-config': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getOidcConfig']
    put: operations['putOidcConfig']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/sessions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getSessions']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/sign-in-options': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getSignInOptions']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['logIn']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['logOut']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AddCandidateChannelRequest: {
      tuning?: null | components['schemas']['TuningParametersRequest']
    }
    ArchiveForgottenResponder: {
      /** Format: int32 */
      forgotten: number | string
    }
    /** @enum {string} */
    AuthMethod: 'local' | 'oidc'
    BaseResponderOfArchiveForgottenResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['ArchiveForgottenResponder']
    }
    BaseResponderOfBoostRefusedResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['BoostRefusedResponder']
    }
    BaseResponderOfBoostStartedResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['BoostStartedResponder']
    }
    BaseResponderOfBroadcastServiceResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['BroadcastServiceResponder']
    }
    BaseResponderOfCollectionStatusResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['CollectionStatusResponder']
    }
    BaseResponderOfDetectedTunersResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['DetectedTunersResponder']
    }
    BaseResponderOfDriverRestartResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['DriverRestartResponder']
    }
    BaseResponderOfDriverStatusResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['DriverStatusResponder']
    }
    BaseResponderOfEpgRebuiltResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['EpgRebuiltResponder']
    }
    BaseResponderOfGuideResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['GuideResponder']
    }
    BaseResponderOfIReadOnlyListOfBroadcastServiceResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['BroadcastServiceResponder'][]
    }
    BaseResponderOfIReadOnlyListOfScanRunResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['ScanRunResponder'][]
    }
    BaseResponderOfIReadOnlyListOfSessionResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['SessionResponder'][]
    }
    BaseResponderOfMeResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['MeResponder']
    }
    BaseResponderOfOidcConfigResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['OidcConfigResponder']
    }
    BaseResponderOfPasswordChangedResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['PasswordChangedResponder']
    }
    BaseResponderOfProgrammeResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['ProgrammeResponder']
    }
    BaseResponderOfProgrammeSearchResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['ProgrammeSearchResponder']
    }
    BaseResponderOfScanApplicationResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['ScanApplicationResponder']
    }
    BaseResponderOfScanProgressResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['ScanProgressResponder']
    }
    BaseResponderOfScanRefusedResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['ScanRefusedResponder']
    }
    BaseResponderOfScanStartedResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['ScanStartedResponder']
    }
    BaseResponderOfSignInOptionsResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['SignInOptionsResponder']
    }
    BaseResponderOfTunerLedgerResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['TunerLedgerResponder']
    }
    BaseResponderOfTunerObservationResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['TunerObservationResponder']
    }
    BaseResponderOfstring: {
      status: boolean
      message: string
      data: null | string
    }
    /** @enum {string} */
    BoostRefusal: 'none' | 'oneIsAlreadyRunning' | 'tooSoonAfterTheLastOne'
    BoostRefusedResponder: {
      refusal: components['schemas']['BoostRefusal']
      /** Format: uuid */
      runningBoostId: null | string
      /** Format: date-time */
      notBefore: null | string
    }
    BoostStartedResponder: {
      /** Format: uuid */
      boostId: string
      /** Format: int32 */
      streams: number | string
    }
    BroadcastServiceResponder: {
      /** Format: int32 */
      networkId: number | string
      /** Format: int32 */
      serviceId: number | string
      name: string
      category: components['schemas']['ServiceCategory']
      /** Format: int32 */
      remoteControlKeyId: null | number | string
      reservableByDefault: boolean
      /** Format: date-time */
      discoveredAt: string
      /** Format: date-time */
      lastSeenAt: string
      /** Format: int32 */
      candidateCount: number | string
      selectedChannel: null | components['schemas']['ScanTargetResponder']
      betterChannel: null | components['schemas']['ScanTargetResponder']
      candidates: components['schemas']['CandidateChannelResponder'][]
    }
    CandidateChannelResponder: {
      /** Format: uuid */
      id: string
      target: components['schemas']['ScanTargetResponder']
      isSelected: boolean
      selection: null | components['schemas']['CandidateSelectionResponder']
      lastMeasurement: null | components['schemas']['ScanMeasurementResponder']
      needsRevalidation: boolean
      rotationState: components['schemas']['RotationState']
      /** Format: int32 */
      consecutiveFailures: number | string
      /** Format: date-time */
      nextAttemptAt: null | string
      /** Format: date-time */
      needsAttentionSince: null | string
      /** Format: date-time */
      discoveredAt: string
      /** Format: date-time */
      lastSeenAt: string
    }
    CandidateSelectionResponder: {
      source: components['schemas']['SelectionSource']
      /** Format: date-time */
      selectedAt: string
      measurement: null | components['schemas']['ScanMeasurementResponder']
    }
    ChangePasswordRequest: {
      currentPassword?: null | string
      newPassword?: null | string
    }
    CollectNowRequest: {
      /** Format: int32 */
      networkId?: null | number | string
      /** Format: int32 */
      transportStreamId?: null | number | string
      /** Format: int32 */
      serviceId?: null | number | string
    }
    CollectionStatusResponder: {
      /** Format: int32 */
      wantedCoverageHours: number | string
      streams: components['schemas']['StreamCollectionStatusResponder'][]
      rescans: components['schemas']['RescanNoticeResponder'][]
    }
    DetectedDeviceResponder: {
      deviceId: string
      detection: components['schemas']['DeviceDetection']
      kinds: components['schemas']['TunerKind'][]
      detail: null | string
    }
    DetectedTunersResponder: {
      devices: components['schemas']['DetectedDeviceResponder'][]
      added: string[]
      missing: string[]
      mismatched: components['schemas']['TunerKindMismatchResponder'][]
    }
    /** @enum {string} */
    DeviceDetection:
      'unspecified' | 'detected' | 'busy' | 'permissionDenied' | 'unreadable'
    /** @enum {string} */
    DriverConnection: 'notConnected' | 'connected' | 'draining'
    DriverHelloResponder: {
      /** Format: int32 */
      protocolVersion: number | string
      instanceId: null | string
      capabilities: string[]
      draining: boolean
    }
    DriverRestartResponder: {
      instanceId: null | string
      /** Format: date-time */
      acceptedAt: string
      /** Format: int32 */
      budgetSeconds: number | string
    }
    DriverStatusResponder: {
      connection: components['schemas']['DriverConnection']
      hello: null | components['schemas']['DriverHelloResponder']
      /** Format: int32 */
      appProtocolVersion: number | string
      missingCapabilities: string[]
      driverUpdateRequired: boolean
      /** Format: date-time */
      observedAt: string
    }
    EpgRebuiltResponder: {
      /** Format: int32 */
      discarded: number | string
      /** Format: int32 */
      generation: number | string
    }
    ForgetArchivedServiceRequest: {
      /** Format: int32 */
      networkId?: null | number | string
      /** Format: int32 */
      serviceId?: null | number | string
      confirm?: null | string
      meansIt?: boolean
    }
    GuideResponder: {
      services: components['schemas']['GuideServiceResponder'][]
      programmes: components['schemas']['ProgrammeResponder'][]
    }
    GuideServiceResponder: {
      /** Format: int32 */
      networkId: number | string
      /** Format: int32 */
      serviceId: number | string
    }
    HealthResponder: {
      status: string
      degraded: string[]
    }
    LoginRequest: {
      username?: null | string
      password?: null | string
    }
    MeResponder: {
      subject: string
      method: components['schemas']['AuthMethod']
    }
    OidcConfigRequest: {
      discoveryUrl?: null | string
      clientId?: null | string
      clientSecret?: null | string
      allowedGroups?: null | string[]
      allowedHostedDomains?: null | string[]
    }
    OidcConfigResponder: {
      configured: boolean
      discoveryUrl: null | string
      clientId: null | string
      secretHeld: boolean
      allowedGroups: string[]
      allowedHostedDomains: string[]
      admitsEveryone: boolean
      reach: components['schemas']['OidcReach']
      redirectUri: string
    }
    /** @enum {string} */
    OidcReach: 'notConfigured' | 'reachable' | 'outOfReach'
    PasswordChangedResponder: {
      /** Format: int32 */
      sessionsEnded: number | string
    }
    ProgrammeGenreResponder: {
      /** Format: int32 */
      kind: number | string
      /** Format: int32 */
      sort: number | string
    }
    ProgrammeItemResponder: {
      heading: string
      text: string
    }
    ProgrammeResponder: {
      id: string
      /** Format: int32 */
      networkId: number | string
      /** Format: int32 */
      serviceId: number | string
      /** Format: int32 */
      eventId: number | string
      /** Format: date-time */
      startsAt: string
      /** Format: date-time */
      endsAt: null | string
      name: string
      summary: string
      isShadow: boolean
      hasSubtitles: boolean
      source: components['schemas']['ProgrammeSource']
      /** Format: int64 */
      revision: number | string
      isArchived: boolean
      genres: components['schemas']['ProgrammeGenreResponder'][]
      items: components['schemas']['ProgrammeItemResponder'][]
      related: components['schemas']['RelatedProgrammeResponder'][]
    }
    ProgrammeSearchResponder: {
      items: components['schemas']['ProgrammeResponder'][]
      /** Format: int32 */
      total: number | string
      /** Format: int32 */
      currentPage: number | string
      /** Format: int32 */
      lastPage: number | string
      /** Format: int32 */
      perPage: number | string
    }
    /** @enum {string} */
    ProgrammeSort: 'startsAt' | 'name'
    /** @enum {string} */
    ProgrammeSource: 'presentFollowing' | 'scheduleBasic' | 'scheduleExtended'
    RebuildEpgRequest: {
      confirm?: null | string
      meansIt?: boolean
    }
    RelatedProgrammeResponder: {
      /** Format: int32 */
      networkId: number | string
      /** Format: int32 */
      serviceId: number | string
      /** Format: int32 */
      eventId: number | string
      kind: components['schemas']['RelationKind']
    }
    /** @enum {string} */
    RelationKind: 'shared' | 'relayed' | 'moved'
    RescanNoticeResponder: {
      /** Format: int32 */
      networkId: number | string
      /** Format: int32 */
      transportStreamId: number | string
      reason: components['schemas']['RescanReason']
      serviceIds: (number | string)[]
      /** Format: date-time */
      noticedAt: string
    }
    /** @enum {string} */
    RescanReason: 'servicesAppeared' | 'servicesVanished'
    RotationDepartureResponder: {
      /** Format: int32 */
      networkId: number | string
      /** Format: int32 */
      serviceId: number | string
      target: components['schemas']['ScanTargetResponder']
      /** Format: int32 */
      consecutiveFailures: number | string
      /** Format: date-time */
      since: string
    }
    /** @enum {string} */
    RotationState: 'active' | 'backingOff' | 'needsAttention'
    ScanApplicationResponder: {
      systems: components['schemas']['TuneSystem'][]
      /** Format: int32 */
      servicesAdded: number | string
      /** Format: int32 */
      servicesUpdated: number | string
      /** Format: int32 */
      servicesRemoved: number | string
      /** Format: int32 */
      channelsAdded: number | string
      /** Format: int32 */
      channelsRemoved: number | string
    }
    /** @enum {string} */
    ScanAttemptOutcome:
      | 'succeeded'
      | 'noLock'
      | 'lockedWithoutData'
      | 'incompleteTables'
      | 'unexpectedStream'
    ScanAttemptResponder: {
      target: components['schemas']['ScanTargetResponder']
      outcome: components['schemas']['ScanAttemptOutcome']
      detail: null | string
      /** Format: int32 */
      observedTransportStreamId: null | number | string
      measurement: null | components['schemas']['ScanMeasurementResponder']
      /** Format: date-time */
      startedAt: string
      /** Format: date-time */
      finishedAt: string
    }
    /** @enum {string} */
    ScanChangeKind: 'added' | 'updated' | 'missing'
    ScanChannelChangeResponder: {
      kind: components['schemas']['ScanChangeKind']
      target: components['schemas']['ScanTargetResponder']
      /** Format: int32 */
      transportStreamId: null | number | string
      measurement: null | components['schemas']['ScanMeasurementResponder']
    }
    ScanDifferenceResponder: {
      added: components['schemas']['ScanServiceChangeResponder'][]
      updated: components['schemas']['ScanServiceChangeResponder'][]
      missing: components['schemas']['ScanServiceChangeResponder'][]
      leftRotation: components['schemas']['RotationDepartureResponder'][]
    }
    ScanMeasurementResponder: {
      /** Format: date-time */
      measuredAt: string
      locked: boolean
      /** Format: int32 */
      cnrMilliDecibels: null | number | string
      /** Format: int64 */
      postViterbiErrorBits: null | number | string
      /** Format: int64 */
      postViterbiTotalBits: null | number | string
    }
    ScanProgressResponder: {
      run: components['schemas']['ScanRunResponder']
      /** Format: int32 */
      attempted: number | string
      /** Format: int32 */
      succeeded: number | string
      /** Format: int32 */
      failed: number | string
      attempts: components['schemas']['ScanAttemptResponder'][]
      difference: null | components['schemas']['ScanDifferenceResponder']
    }
    ScanRefusedResponder: {
      /** Format: uuid */
      runningScanId: null | string
    }
    ScanRunResponder: {
      /** Format: uuid */
      scanId: string
      state: components['schemas']['ScanRunState']
      driverInstanceId: null | string
      /** Format: date-time */
      startedAt: string
      /** Format: date-time */
      finishedAt: null | string
      reason: null | string
    }
    /** @enum {string} */
    ScanRunState:
      'running' | 'completed' | 'failed' | 'cancelled' | 'interrupted'
    ScanServiceChangeResponder: {
      kind: components['schemas']['ScanChangeKind']
      /** Format: int32 */
      networkId: number | string
      /** Format: int32 */
      serviceId: number | string
      name: string
      category: components['schemas']['ServiceCategory']
      channels: components['schemas']['ScanChannelChangeResponder'][]
    }
    ScanStartedResponder: {
      /** Format: uuid */
      scanId: string
    }
    ScanTargetResponder: {
      system: components['schemas']['TuneSystem']
      /** Format: int32 */
      physicalChannel: number | string
      /** Format: int32 */
      transportStreamId: null | number | string
    }
    SelectedChannelRequest: {
      /** Format: uuid */
      candidateChannelId?: null | string
    }
    /** @enum {string} */
    SelectionSource: 'manual' | 'autoSwitch' | 'scan'
    /** @enum {string} */
    ServiceCategory:
      'television' | 'radio' | 'data' | 'oneSeg' | 'temporary' | 'other'
    ServiceCoverageResponder: {
      /** Format: int32 */
      serviceId: number | string
      /** Format: date-time */
      coveredUntil: null | string
      meetsWantedCoverage: boolean
    }
    /** @enum {string} */
    SessionPurpose:
      'unspecified' | 'recording' | 'live' | 'survey' | 'scan' | 'surveyNow'
    SessionResponder: {
      id: string
      method: components['schemas']['AuthMethod']
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      lastUsedAt: string
      deviceLabel: string
      current: boolean
    }
    SignInOptionsResponder: {
      identityProvider: boolean
      providerName: null | string
      reach: components['schemas']['OidcReach']
    }
    StartScanRequest: {
      systems?: null | components['schemas']['TuneSystem'][]
      channels?: null | components['schemas']['TuningParametersRequest'][]
    }
    /** @enum {string} */
    StreamCollectionOutcome:
      | 'neverVisited'
      | 'complete'
      | 'basicOnly'
      | 'incomplete'
      | 'interrupted'
      | 'noLock'
      | 'noBytes'
    StreamCollectionStatusResponder: {
      /** Format: int32 */
      networkId: number | string
      /** Format: int32 */
      transportStreamId: null | number | string
      tuning: components['schemas']['StreamTuningResponder']
      rotation: components['schemas']['StreamRotationResponder']
      outcome: components['schemas']['StreamCollectionOutcome']
      /** Format: date-time */
      lastAttemptedAt: null | string
      /** Format: date-time */
      lastCompletedAt: null | string
      /** Format: int32 */
      consecutiveIncomplete: number | string
      /** Format: int32 */
      lastDurationMilliseconds: number | string
      /** Format: date-time */
      notBefore: null | string
      serviceIds: (number | string)[]
      coverage: components['schemas']['ServiceCoverageResponder'][]
      tally: components['schemas']['VisitTallyResponder'][]
    }
    StreamRotationResponder: {
      state: components['schemas']['RotationState']
      /** Format: int32 */
      consecutiveFailures: number | string
      /** Format: date-time */
      nextAttemptAt: null | string
      /** Format: date-time */
      needsAttentionSince: null | string
    }
    StreamTuningResponder: {
      system: components['schemas']['TuneSystem']
      /** Format: int32 */
      physicalChannel: number | string
      /** Format: int32 */
      transportStreamId: null | number | string
    }
    ToggleTunerRequest: {
      disabled?: null | boolean
    }
    /** @enum {string} */
    TuneSystem: 'unspecified' | 'isdbT' | 'isdbSBs' | 'isdbSCs110'
    TunerEntryRequest: {
      deviceId?: null | string
      disabled?: boolean
      lnbPower?: boolean
    }
    TunerEntryResponder: {
      deviceId: string
      disabled: boolean
      lnbPower: boolean
    }
    /** @enum {string} */
    TunerHealthLevel: 'unspecified' | 'healthy' | 'degraded' | 'faulted'
    /** @enum {string} */
    TunerKind: 'unspecified' | 'terrestrial' | 'satellite'
    TunerKindMismatchResponder: {
      deviceId: string
      observed: components['schemas']['TunerKind']
      detected: components['schemas']['TunerKind'][]
    }
    TunerLedgerRequest: {
      tuners?: null | components['schemas']['TunerEntryRequest'][]
    }
    TunerLedgerResponder: {
      desired: components['schemas']['TunerEntryResponder'][]
      savedHash: null | string
      loadedHash: null | string
      drifted: boolean
      observed: null | components['schemas']['TunerObservationResponder'][]
      /** Format: date-time */
      observedAt: null | string
      observationFailure: null | string
    }
    TunerObservationResponder: {
      deviceId: string
      kind: components['schemas']['TunerKind']
      state: components['schemas']['TunerState']
      detail: null | string
      health: components['schemas']['TunerHealthLevel']
      disablePending: boolean
      lnbPowered: boolean
      healthDetail: null | string
      /** Format: date-time */
      healthChangedAt: null | string
      sessionId: null | string
      sessionPurpose: components['schemas']['SessionPurpose']
      /** Format: date-time */
      sessionStartedAt: null | string
      /** Format: date-time */
      sessionEndsAt: null | string
      sessionTuning: null | components['schemas']['ScanTargetResponder']
    }
    /** @enum {string} */
    TunerState:
      'unspecified' | 'idle' | 'busy' | 'disabled' | 'faulted' | 'draining'
    TuningParametersRequest: {
      system?: components['schemas']['TuneSystem']
      /** Format: int32 */
      physicalChannel?: null | number | string
      /** Format: int32 */
      transportStreamId?: null | number | string
    }
    VisitTallyResponder: {
      /** Format: int32 */
      serviceId: number | string
      /** Format: int32 */
      tableId: number | string
      /** Format: int32 */
      lastTableId: number | string
      /** Format: int32 */
      segmentsDeclared: number | string
      /** Format: int32 */
      segmentsHeard: number | string
      /** Format: int32 */
      sectionsDeclared: number | string
      /** Format: int32 */
      sectionsHeard: number | string
      /** Format: int32 */
      versionChanges: number | string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getDetectedTuners: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDetectedTunersResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDetectedTunersResponder']
        }
      }
      /** @description Not Implemented */
      501: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDetectedTunersResponder']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDetectedTunersResponder']
        }
      }
    }
  }
  getTuners: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfTunerLedgerResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfTunerLedgerResponder']
        }
      }
      /** @description Not Implemented */
      501: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfTunerLedgerResponder']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfTunerLedgerResponder']
        }
      }
    }
  }
  putTuners: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TunerLedgerRequest']
        'text/json': components['schemas']['TunerLedgerRequest']
        'application/*+json': components['schemas']['TunerLedgerRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfTunerLedgerResponder']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfTunerLedgerResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfTunerLedgerResponder']
        }
      }
      /** @description Not Implemented */
      501: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfTunerLedgerResponder']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfTunerLedgerResponder']
        }
      }
    }
  }
  patchTuner: {
    parameters: {
      query?: never
      header?: never
      path: {
        deviceId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ToggleTunerRequest']
        'text/json': components['schemas']['ToggleTunerRequest']
        'application/*+json': components['schemas']['ToggleTunerRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfTunerObservationResponder']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfTunerObservationResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfTunerObservationResponder']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfTunerObservationResponder']
        }
      }
      /** @description Not Implemented */
      501: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfTunerObservationResponder']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfTunerObservationResponder']
        }
      }
    }
  }
  addCandidateChannel: {
    parameters: {
      query?: never
      header?: never
      path: {
        networkId: number
        serviceId: number
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json':
          null | components['schemas']['AddCandidateChannelRequest']
        'text/json': null | components['schemas']['AddCandidateChannelRequest']
        'application/*+json':
          null | components['schemas']['AddCandidateChannelRequest']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
    }
  }
  deleteCandidateChannel: {
    parameters: {
      query?: never
      header?: never
      path: {
        networkId: number
        serviceId: number
        candidateChannelId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
    }
  }
  getService: {
    parameters: {
      query?: never
      header?: never
      path: {
        networkId: number
        serviceId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
    }
  }
  listServices: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfIReadOnlyListOfBroadcastServiceResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfIReadOnlyListOfBroadcastServiceResponder']
        }
      }
    }
  }
  putSelectedChannel: {
    parameters: {
      query?: never
      header?: never
      path: {
        networkId: number
        serviceId: number
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json':
          null | components['schemas']['SelectedChannelRequest']
        'text/json': null | components['schemas']['SelectedChannelRequest']
        'application/*+json':
          null | components['schemas']['SelectedChannelRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBroadcastServiceResponder']
        }
      }
    }
  }
  applyScan: {
    parameters: {
      query?: never
      header?: never
      path: {
        scanId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanApplicationResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanApplicationResponder']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanApplicationResponder']
        }
      }
      /** @description Gone */
      410: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanApplicationResponder']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanApplicationResponder']
        }
      }
    }
  }
  cancelScan: {
    parameters: {
      query?: never
      header?: never
      path: {
        scanId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanProgressResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanProgressResponder']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanProgressResponder']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanProgressResponder']
        }
      }
    }
  }
  getScan: {
    parameters: {
      query?: never
      header?: never
      path: {
        scanId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanProgressResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanProgressResponder']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanProgressResponder']
        }
      }
    }
  }
  listScanRuns: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfIReadOnlyListOfScanRunResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfIReadOnlyListOfScanRunResponder']
        }
      }
    }
  }
  startScan: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': null | components['schemas']['StartScanRequest']
        'text/json': null | components['schemas']['StartScanRequest']
        'application/*+json': null | components['schemas']['StartScanRequest']
      }
    }
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanStartedResponder']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanStartedResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanRefusedResponder']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanStartedResponder']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfScanStartedResponder']
        }
      }
    }
  }
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponder']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponder']
        }
      }
    }
  }
  collectNow: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': null | components['schemas']['CollectNowRequest']
        'application/*+json': null | components['schemas']['CollectNowRequest']
      }
    }
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBoostStartedResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBoostStartedResponder']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBoostRefusedResponder']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfBoostStartedResponder']
        }
      }
    }
  }
  forgetArchivedService: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json':
          null | components['schemas']['ForgetArchivedServiceRequest']
        'application/*+json':
          null | components['schemas']['ForgetArchivedServiceRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfArchiveForgottenResponder']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfArchiveForgottenResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfArchiveForgottenResponder']
        }
      }
    }
  }
  getCollectionStatus: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfCollectionStatusResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfCollectionStatusResponder']
        }
      }
    }
  }
  getProgramme: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfProgrammeResponder']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfProgrammeResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfProgrammeResponder']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfProgrammeResponder']
        }
      }
    }
  }
  getProgrammeGuide: {
    parameters: {
      query?: {
        type?: components['schemas']['TuneSystem']
        from?: string
        to?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfGuideResponder']
        }
      }
      /** @description Not Modified */
      304: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfGuideResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfGuideResponder']
        }
      }
    }
  }
  rebuildEpg: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': null | components['schemas']['RebuildEpgRequest']
        'application/*+json': null | components['schemas']['RebuildEpgRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfEpgRebuiltResponder']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfEpgRebuiltResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfEpgRebuiltResponder']
        }
      }
    }
  }
  searchProgrammes: {
    parameters: {
      query?: {
        keyword?: string
        from?: string
        to?: string
        sort?: components['schemas']['ProgrammeSort']
        descending?: boolean
        page?: number | string
        perPage?: number | string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfProgrammeSearchResponder']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfProgrammeSearchResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfProgrammeSearchResponder']
        }
      }
    }
  }
  getDriverStatus: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDriverStatusResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDriverStatusResponder']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDriverStatusResponder']
        }
      }
    }
  }
  restartDriver: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDriverRestartResponder']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDriverRestartResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDriverRestartResponder']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDriverRestartResponder']
        }
      }
      /** @description Not Implemented */
      501: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDriverRestartResponder']
        }
      }
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDriverRestartResponder']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDriverRestartResponder']
        }
      }
    }
  }
  changePassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json':
          null | components['schemas']['ChangePasswordRequest']
        'application/*+json':
          null | components['schemas']['ChangePasswordRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfPasswordChangedResponder']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfPasswordChangedResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfPasswordChangedResponder']
        }
      }
    }
  }
  deleteSession: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfstring']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfstring']
        }
      }
    }
  }
  getMe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfMeResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfMeResponder']
        }
      }
    }
  }
  getOidcConfig: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfOidcConfigResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfOidcConfigResponder']
        }
      }
    }
  }
  putOidcConfig: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': null | components['schemas']['OidcConfigRequest']
        'application/*+json': null | components['schemas']['OidcConfigRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfOidcConfigResponder']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfOidcConfigResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfOidcConfigResponder']
        }
      }
    }
  }
  getSessions: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfIReadOnlyListOfSessionResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfIReadOnlyListOfSessionResponder']
        }
      }
    }
  }
  getSignInOptions: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfSignInOptionsResponder']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfSignInOptionsResponder']
        }
      }
    }
  }
  logIn: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': null | components['schemas']['LoginRequest']
        'application/*+json': null | components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfMeResponder']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfMeResponder']
        }
      }
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfMeResponder']
        }
      }
      /** @description The request failed before it could answer for itself. The body carries the usual envelope with no data. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfMeResponder']
        }
      }
    }
  }
  logOut: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
