/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/driver/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getDriverStatus']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    BaseResponderOfDriverStatusResponder: {
      status: boolean
      message: string
      data: null | components['schemas']['DriverStatusResponder']
    }
    /** @enum {string} */
    DriverConnection: 'notConnected' | 'connected' | 'draining'
    DriverHelloResponder: {
      /** Format: int32 */
      protocolVersion: number | string
      instanceId: null | string
      capabilities: string[]
      draining: boolean
    }
    DriverStatusResponder: {
      connection: components['schemas']['DriverConnection']
      hello: null | components['schemas']['DriverHelloResponder']
      /** Format: int32 */
      appProtocolVersion: number | string
      missingCapabilities: string[]
      driverUpdateRequired: boolean
      /** Format: date-time */
      observedAt: string
    }
    HealthResponder: {
      status: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponder']
        }
      }
    }
  }
  getDriverStatus: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDriverStatusResponder']
        }
      }
      /** @description Unauthenticated. The default-deny middleware answers with an empty body. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseResponderOfDriverStatusResponder']
        }
      }
    }
  }
}
